version: '3.7'

services:
    db:
        container_name: 'ticket-mongodb'
        image: 'mongo:4'
        ports:
            - '$MONGODB_EXPOSED_PORT:$MONGODB_PORT'
        env_files:
            - ./.env.mongodb
